- name: Demo on Parameters
  hosts: localhost
  tasks:
    - name: Get a Parameter from Parameter Store
      anisble.builtin.debug:
         msg: "{{ lookup('aws_ssm', 'test', region='us-east-1' ) }}"